### ISSUE TITLE
paths[0]

### ISSUE THREAD

**Issue by MadBl1ss** [Widiskel/drft-party-bot#5]
Keep getting an error after starting the bot.
"Error: Error reading sessions directory: TypeError [ERR_INVALID_ARG_TYPE]: The "paths[0]" argument must be of type string. Received undefined, at Helper.getSession (file:///C:/Users/*/drft-party-bot-master/src/utils/helper.js:84:13)"

**Comment by MuscleeMuseum** [comment]
You have an error line in the config file, delete all sessions, and fill everything again

**Comment by MadBl1ss** [comment]
> You have an error line in the config file, delete all sessions, and fill everything again

did it 5 times, doesn't help. After creating new session a new problem arises:
"Status : WSS Connected...
Delay : Delaying for 0 Hours 0 Minutes 1 Seconds"

**Comment by Widiskel** [comment]
> Keep getting an error after starting the bot. "Error: Error reading sessions directory: TypeError [ERR_INVALID_ARG_TYPE]: The "paths[0]" argument must be of type string. Received undefined, at Helper.getSession (file:///C:/Users/*/drft-party-bot-master/src/utils/helper.js:84:13)"

just need to re start the bot again. this error is usually show after session creation and bot start.

**Comment by Widiskel** [comment]
> > You have an error line in the config file, delete all sessions, and fill everything again
> 
> did it 5 times, doesn't help. After creating new session a new problem arises: "Status : WSS Connected... Delay : Delaying for 0 Hours 0 Minutes 1 Seconds"

they fix the API already now all msg encrypted so it maybe need some update on bot
