### ISSUE TITLE
ask

### ISSUE THREAD

**Issue by kingvavasav** [Widiskel/drft-party-bot#7]
kelebihan make sessions apaan bg?
ane buat sessions stuck aja ga bsa itu knpa yah?

**Comment by Widiskel** [comment]
> kelebihan make sessions apaan bg?
> ane buat sessions stuck aja ga bsa itu knpa yah?

kelebihan make session ga ada expirednya bg soalnya sma kyk buka app lgsng lewat tele

stuck gmn bg  ? klo bot drft ini sih udh di fix sma devnya. skrng datanya di encrypt smua jd dan gw blm nemu cara decryptnya

**Comment by kingvavasav** [comment]
> > kelebihan make sessions apaan bg?
> > ane buat sessions stuck aja ga bsa itu knpa yah?
> 
> kelebihan make session ga ada expirednya bg soalnya sma kyk buka app lgsng lewat tele
> 
> stuck gmn bg ? klo bot drft ini sih udh di fix sma devnya. skrng datanya di encrypt smua jd dan gw blm nemu cara decryptnya

kalau fix ini gmna bg The system cannot find the path specified.
![2024-09-03_083723](https://github.com/user-attachments/assets/7d03f506-9b50-4848-a35c-bfd90e4d168b)

**Comment by Widiskel** [comment]
itu salah path bg, klo windows buka aja manual foldernya lewat explorer , trus ke bagian path explorernya baru ketik `cmd`
